//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.StudentInfoes = new HashSet<StudentInfo>();
        }
    
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
    
        public virtual Department Department1 { get; set; }
        public virtual Department Department2 { get; set; }
        public virtual ICollection<StudentInfo> StudentInfoes { get; set; }
    }
}
